<?php if (!empty($this->issues)) : ?>
    <h2><?php echo $this->tr->_('DASHBOARD_WELCOME_TITLE'); ?></h2><br />
    <h2><?php echo $this->tr->_('CRITICAL_SETUP_ISSUES'); ?></h2>
    <p><?php echo $this->tr->_('CRITICAL_SETUP_ISSUES_INTRO'); ?></p>
    <ul>
        <?php foreach ($this->issues as $name => $message) :?>
            <li><?php echo $message; ?><br /><br /></li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <h2><?php echo $this->tr->_('AMAZING_WELCOME'); ?></h2>
<?php endif; ?>