<script type="text/javascript" src="/scripts/syntaxhighlighter/shCore.js"></script>
<script type="text/javascript" src="/scripts/syntaxhighlighter/shBrushJScript.js"></script>
<script type="text/javascript" src="/scripts/syntaxhighlighter/shBrushPhp.js"></script>
<script type="text/javascript" src="/scripts/syntaxhighlighter/shBrushPlain.js"></script>
<script type="text/javascript" src="/scripts/syntaxhighlighter/shBrushXml.js"></script>
<script type="text/javascript" src="/scripts/customBrushHeaders.js"></script>
<script type="text/javascript" src="/scripts/beautify.js"></script>
<link type="text/css" rel="stylesheet" href="/css/syntaxhighlighter/shCore.css"/>
<link type="text/css" rel="stylesheet" href="/css/syntaxhighlighter/shThemeDefault.css"/>
<script type="text/javascript">
    SyntaxHighlighter.config.clipboardSwf = '/scripts/syntaxhighlighter/clipboard.swf';
    var highlight_response = function () {
        window.SyntaxHighlighter.highlight()
    };
</script>

<?php
echo $this->form;
?>

<div id="submitter-div"><input type="button" id="submitter" value="<?php echo $this->tr->_('RUN_TEST'); ?>" /></div>
<div id="testing"><img id="loading" src="/gifs/ajax-loader.gif" alt="Loading" /></div>

<style type="text/css">
#container .main {
    background-color: white !important;
    background-image: none;
}
    #container .sidenav {
        display: none;
    }

    #container .content {
        display: block;
        float: none;
        padding: 0;
        width: 780px;
    }

    form {
        padding: 10px !important;
        width: 760px;
    }
        #framer {
            width: 100%;
            height: 400px;
            border: 1px solid black;;
        }
</style>
<br />

<h2 style="display: none" id="request-header"><?php echo $this->tr->_('REQUEST'); ?></h2>
<div id="request-container"></div>
<h2 style="display: none" id="post-fields-header"><?php echo $this->tr->_('POST_FIELDS'); ?></h2>
<div id="post-fields-container"></div>

<h2 style="display: none" id="response-header"><?php echo $this->tr->_('RESPONSE'); ?></h2>
<div id="response-container"></div>

<script type="text/javascript">
    var url = 'api.frapi';

    $('#action').change(function() {
        var selected = $(this).val();
        var selectedText = $('#action :selected').text();
        var type  = (selected.match(/^[0-9]+$/)) ? ("action") : ("route")

        $('#params').empty();
        if ("route" == type) {
            $('#query_uri').val(selectedText);
        } else {
            $('#query_uri').val("?action=" + selectedText);
        }
    });

    $('#action').change();

    $("form input").keypress(function (e) {
        if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
            $('#submitter').click();
            return false;
        } else {
            return true;
        }
    });

    function addParamInput(paramName, paramValue)
    {
        var value = paramName ? paramName + "=" : "";
        var value = paramValue ? value + paramValue : "";
        $("#params").append('<p><input type="text" name="param[]" value="'+value+'" /> <img src="/images/delete.png" class="remove" /></p>');
        $("#params input:last").focus();
    }

    $(function(){
        $("#add").live("click", function(ev) {
            addParamInput();
        });

        $(".remove").live('click', function () {
            var target = $(this);
            target.parent().remove();
        });
    });


    $('#emailkey').change(function() {
        var selected = $(this).val();
        var selectedText = $('#emailkey :selected').text();
        var valid  = (selected.length > 0);

        if (valid) {
            var split = selectedText.split(" / ", 2);
            $('#email').val(split[0]);
            $('#key').val(split[1]);
        }
    });

    $('#submitter').live('click', function() {

        $('#submitter').attr('disabled', true)
                       .attr('value', '<?php echo $this->tr->_('TESTING'); ?>...');
        $('#testing').show();

        var queryURI = $('#query_uri').val();
        var method   = $('#method').val();
        var email    = $('#email').val();
        var key      = $('#key').val();
        var format   = $('#format').val();


        var url      = $('#url').val();
        var ssl      = $('#ssl').is(':checked');

        var extraParams = new Array();

        $("#message").remove();

        jQuery.each($('#params input'), function(){
            extraParams[extraParams.length] = $(this).val();
        });

        if (!queryURI) {
            alert('<?php echo $this->tr->_('NO_QUERY_URI'); ?>?'); return false;
        }

        queryURI += '.' + format.toLowerCase();

        var finalParams = 'email=' + escape(email);
        finalParams += '&secretKey=' + key;

        switch (method.toLowerCase()) {
            case 'get':
            case 'post':
            case 'delete':
            case 'put':
                method = method.toLowerCase();
                break;
            default:
                method = 'get';
                break;
        }

        finalParams += '&method=' + method;
        finalParams += '&url=' + url;
        finalParams += '&query_uri=' + escape(queryURI);
        if (ssl === true) {
            finalParams += '&ssl=true';
        }

        if (extraParams.length > 0) {
            for (var i = 0; i < extraParams.length; i++) {
                finalParams += '&param[]=' + escape(extraParams[i]);
            }
        }

        if (format.indexOf('JSON') >= 0) {
            $('#beautify').live('click', function() {
                var code = $('#response-container').attr('data-content')
                code = js_beautify(code);
                $('#response-container div.syntaxhighlighter').remove();
                $('#response-container').append('<pre id="response" />');
                $('pre#response').html(code).addClass('brush: jscript');
                highlight_response();
            });
        }

        $.ajax( {
           type:    "GET",
           url:     "/tester/ajax",
           data:    finalParams,
           success: function(data) {
               var brush = "jscript";
               switch (format.toLowerCase()) {
                   case "xml":
                       brush = "xml";
                       break;
                   case "php":
                       brush = "php";
                       break;
                   case "cli":
                       brush = "plain";
                       break;
               }

               var RequestString = '<?php echo $this->tr->_('REQUEST'); ?>';
               var ResponseString = '<?php echo $this->tr->_('RESPONSE'); ?>';
               var CodeString = '<?php echo $this->tr->_('CODE'); ?>';

               $('#request-header').html(RequestString + " ("+ data.method +")").show();
               $('#response-header').html(ResponseString + " (" + CodeString + " "+ data.status +")").show();
               $('#request-container').empty().append(
                   $('<input>').attr({id: "#request_url", style: "width: 100%"}).val(data.request_url)
               );

               $('#post-fields-header').hide();
               $('#post-fields-container').empty();
               if (data.request_post_fields) {
                   $('#post-fields-header').show();
                   $('#post-fields-container').append(
                       $('<textarea>').attr({id: "#post-fields-textarea", style: "width: 100%"}).val(data.request_post_fields)
                   );
               }

               $('#response-container').empty();
               $('#response-container').append(
                   $('<pre>').attr('id', '#response_headers').addClass("brush: headers").html(data.response_headers)
               );

               var responseContent = '';
               responseContent = $('<pre>').attr('id', 'response').addClass("brush: " + brush).html(unescape(data.content));


               $('#response-container').attr('data-content', data.content).append(
                   $('<h2><?php echo $this->tr->_('CONTENT_BODY'); ?></h2>')
               ).append(responseContent);


               var abeauty = $('<a id="beautify">Beautify</a>').css({cursor: 'pointer'});
               if (format.indexOf('JSON') >= 0) {
                   $('#response-container').append(abeauty);
               } else {
                   $('#beautify').remove();
               }

               highlight_response();


               $('#submitter').attr('disabled', false)
                              .attr('value', '<?php echo $this->tr->_('RUN_TEST'); ?>');
            
               var inHistory = false;
               var uri       = queryURI.replace('\.' + format.toLowerCase(), '');
               $('#action optgroup[label=History] option').each(function() {
                   if ($(this).val() == uri) {
                     inHistory = true;
                   }
               });
               if (!inHistory) {
                   $('#action optgroup[label=History]').append('<option value="' + uri + '"" selected="selected">' + uri + '</option>');
               }

               $('#testing').hide();
           },
           dataType: "json",
           error: function (XMLHttpRequest, textStatus, errorThrown) {
               if (XMLHttpRequest.status == 403) {
                   var ResponseString = '<?php echo $this->tr->_('TESTER_REQUEST_ERROR'); ?>';
                   $(".content").prepend($('<div>').attr('id', 'message').html(ResponseString));
               }

               $('#submitter').attr('disabled', false)
                              .attr('value', '<?php echo $this->tr->_('RUN_TEST'); ?>');
               $('#testing').hide();
               this;
           }
        });

        return false;
    });

    $('#action').live('change', function() {
        var inHistory = false;
        var queryURI  = $('#query_uri').val();

        $('#action optgroup[label=History] option').each(function() {
            if ($(this).val() == queryURI) {
                inHistory = true;
            }
        });

        if (inHistory) {
            $.ajax({
                type:    "GET",
                url:     "/tester/history",
                data:    "url=" + escape(queryURI),
                success: function(data) { 
                    $("#query_uri").val(data.query_uri);
                    $("#format").attr("value", data.format.toUpperCase());
                    $("#method").attr("value", data.method.toLowerCase());
                    $("#email").val(data.email);
                    $("#key").val(data.secretKey);
                    $("#url").val(data.url);

                    if (typeof(data.ssl) != "undefined") {
                        $("#ssl").attr("checked", data.ssl); 
                    }

                    if (typeof(data.param) != "undefined") {
                        for(i in data.param) {
                            var param_parts = data.param[i].split("=")
                            addParamInput(param_parts[0], param_parts[1]);
                        }
                    }
                },
                dataType: "json",
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert('<?php echo $this->tr->_('HISTORY_ERROR'); ?>');
                }
            });
        }
    });
</script>

