<h2><?php echo $this->tr->_('DATABASE_CONFIGURATION'); ?></h2>
<?php if (empty($this->configs)) : ?>
<?php echo $this->tr->_('NO_DATABASE_CONFIGURATION_YET'); ?>. <a href="/database/add"><?php echo $this->tr->_('ADD_SOME'); ?></a><br />
<?php else: ?>
<br /><br />
<a href="/database/edit"><?php echo $this->tr->_('EDIT_DATABASE_CONFIGURATION'); ?></a>
<br /><br />
<table id="list">
 <thead>
  <tr>
    <th><?php echo $this->tr->_('KEY'); ?></th>
    <th><?php echo $this->tr->_('VALUE'); ?></th>
    <th><?php echo $this->tr->_('TYPE'); ?></th>
  </tr>
 </thead>
 <tbody>
 <?php foreach ($this->configs as $d) : ?>
  <tr>
    <td><?php echo $d['key']; ?></td>
    <td><?php echo $d['value']; ?></td>
    <td><?php echo $this->tr->_('MAIN'); ?></td>
  </tr>
 <?php endforeach; ?>
 </tbody>
</table>

<?php endif; ?>