<div style="float: left"><form id="filter-form">Filter: <input name="filter" id="filter" value="" maxlength="30" size="30" type="text"></form></div>
<br /><br /><br /><br /><br />

    <table id="list">
     <thead>
      <tr>
        <th>Name</th>
        <th>Visibility</th>
        <th>Enabled</th>
        <th>Action</th>
      </tr>
     </thead>
     <tbody>
<?php foreach ($this->data as $key => $d) : if (is_array($d) && !empty($d)) : ?>
      <tr>
        <td><?php echo $d['name']; ?></td>
        <?php $visibility = ($d['public'] == '1' || $d['public'] === null) ? 'Public' : 'Private'; ?>
        <td class="visibility"><?php echo $visibility; ?></td>
        <?php
            if ($d['enabled'] == '1') {
                $enabled = 'Yes';
                $class   = 'enabled';
            } else {
                $enabled = 'No';
                $class   = 'disabled';
            }
        ?>
        <td class="<?php echo $class; ?>"><?php echo $enabled; ?></td>
        <td style="text-align: center;">
            <a href="/action/edit/id/<?php echo $d['hash']; ?>">Edit</a> |
            <?php
                if ($d['enabled'] == '1') {
//                    echo '<a href="#">Disable</a>';
                } else {
//                    echo '<a href="#">Enable</a>';
                }
            ?>
            <a href="/action/delete/id/<?php echo $d['hash']; ?>">Delete</a>
        </td>
      </tr>
<?php endif; endforeach; ?>
     </tbody>
    </table>


<script type="text/javascript">
$(function() {
    var t = $('table#list')
    t.tablesorter({
        sortList:[[0,0]],
        widgets: ['zebra'],
        dateFormat: 'dd.mm.yyyy',
        headers: {
            3: { sorter: false }
        }
    });


  $("#filter").keyup(function() {
    $.uiTableFilter(t, this.value);
  })

  $('#filter-form').submit(function(){
    t.find("tbody > tr:visible > td:eq(1)").mousedown();
    return false;
  }).focus(); //Give focus to input field
});
</script>