<div style="float: left"><form id="filter-form">Filter: <input name="filter" id="filter" value="" maxlength="30" size="30" type="text"></form></div>
<br /><br /><br /><br /><br />

    <table id="list">
     <thead>
      <tr>
        <th>Name</th>
        <th>Message</th>
        <th>Action</th>
      </tr>
     </thead>
     <tbody>
<?php foreach ($this->data as $key => $d) : if (is_array($d) && !empty($d)) : ?>
      <tr>
        <td><?php echo $d['name']; ?></td>
        <td><?php echo $d['message']; ?></td>
        <td style="text-align: center;">
            <a href="/errors/edit/id/<?php echo $d['hash']; ?>">Edit</a> | <a href="/errors/delete/id/<?php echo $d['hash']; ?>">Delete</a>
        </td>
      </tr>
<?php endif; endforeach; ?>
     </tbody>
    </table>


<script type="text/javascript">
$(function() {
    var t = $('table#list')
    t.tablesorter({
        sortList:[[0,0]],
        widgets: ['zebra'],
        dateFormat: 'dd.mm.yyyy',
        headers: {
            2: { sorter: false }
        }
    });


  $("#filter").keyup(function() {
    $.uiTableFilter(t, this.value);
  })

  $('#filter-form').submit(function(){
    t.find("tbody > tr:visible > td:eq(1)").mousedown();
    return false;
  }).focus(); //Give focus to input field
});
</script>