<form id="login" action="login" method="post">
 <div class="field-block">
  <label for="handle"><?php echo $this->tr->_('USERNAME');?></label>
  <input type="text" name="handle" id="handle" value="" />
 </div>

 <div class="field-block">
  <label for="passwd"><?php echo $this->tr->_('PASSWORD');?></label>
  <input type="password" name="password" id="password" value="" />
 </div>

 <div class="field-block">
  <input type="submit" name="login" value="<?php echo $this->tr->_('LOGIN');?>" />
 </div>
</form>

<script type="text/javascript">
$(document).ready(function() {
    $("#handle").focus();
});
</script>