<form id="login" action="login" method="post">
 <div class="field-block">
  <label for="handle">Username</label>
  <input type="text" name="handle" id="handle" value="" />
 </div>

 <div class="field-block">
  <label for="passwd">Password</label>
  <input type="password" name="password" id="password" value="" />
 </div>

 <div class="field-block">
  <input type="submit" name="login" value="Login" />
 </div>
</form>