<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1"/>
	<meta name="description" content="echolibre FRAPI Admin Interface."/>
	<meta name="author" content="echolibre"/> 
	<link rel="shortcut icon" href="/gifs/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="/css/template.css" media="all"/>
	<link rel="stylesheet" type="text/css" href="/css/frapi-specific.css" media="all"/>
	<script src="/javascript/jquery.js" type="text/javascript"></script>
	<script src="/javascript/jquery.metadata.js" type="text/javascript"></script>
	<script src="/javascript/jquery.uitablefilter.js" type="text/javascript"></script>
	<script src="/javascript/jquery.tablesorter.min.js" type="text/javascript"></script>
	<script type="text/javascript">
	   $(function() {
	       $('#sync').live('click', function() {
	           document.location.href = '/action/sync';
	       });
	   });
	</script>
	<!-- compliance patch for microsoft browsers -->
	<!--[if lt IE 8]><script src="/javascript/IE8.js" type="text/javascript"></script><![endif]-->
	<title>FRAPI Admin Interface</title>
</head>

<body>

<div id="top">				
	<div id="header">
		<div class="left">&nbsp;</div>

		<div class="right">
		    <?php if (!is_null($this->user)) : ?>
		    <div class="inright">
		    <h2>Welcome</h2>
		    <p><i><strong>"Sync'ing"</strong></i>: Synchronizing your codebase with the actions you created in "<strong><a href="/action" title="Action management">Actions</a></strong>"</p>
			<button alt="Synchronize Development Codebase" id="sync">Sync Now</button>
			</div>
			<?php else: ?>
		    <div class="inright">
                <h2>Welcome</h2>
                <p>You are using the FRAPI admin system.</p>
            </div>
			<?php endif;?>
		</div>
	</div>	
</div>

	<div id="container">