<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<meta name="description" content="echolibre FRAPI <?php echo $this->tr->_('ADMIN_INTERFACE'); ?>."/>
	<meta name="author" content="echolibre"/> 
	<link rel="shortcut icon" href="/gifs/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="/css/template.css" media="all"/>
	<link rel="stylesheet" type="text/css" href="/css/frapi-specific.css" media="all"/>
	<script src="/scripts/jquery.js" type="text/javascript"></script>
	<script src="/scripts/jquery.metadata.js" type="text/javascript"></script>
	<script src="/scripts/jquery.uitablefilter.js" type="text/javascript"></script>
	<script src="/scripts/jquery.tablesorter.min.js" type="text/javascript"></script>
	<!-- compliance patch for microsoft browsers -->
	<!--[if lt IE 8]><script src="/scripts/IE8.js" type="text/javascript"></script><![endif]-->
    <link id="bespin_base" href="/bespin" />
    
	<title>FRAPI <?php echo $this->tr->_('ADMIN_INTERFACE'); ?></title>
</head>

<body>

<div id="top">				
	<div id="header">
		<div class="left">&nbsp;</div>

		<div class="right">
		    <?php if (!is_null($this->user)) : ?>
		    <div class="inright">
		    <h2><?php echo $this->tr->_('WELCOME'); ?></h2>
		    <p><?php echo $this->tr->_('SYNCING_MESSAGE'); ?></p>
			<button alt="<?php echo $this->tr->_('SYNCRONIZE_TITLE'); ?>" id="sync"><?php echo $this->tr->_('SYNC')?></button>
			</div>
			<?php else: ?>
		    <div class="inright">
                <h2><?php echo $this->tr->_('WELCOME'); ?></h2>
                <p><?php echo $this->tr->_('YOU_ARE_USING_FRAPI'); ?></p>
            </div>
			<?php endif;?>
		</div>
	</div>	
</div>

	<div id="container">
